//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCinema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cevaplar
    {
        public int id { get; set; }
        public string kime { get; set; }
        public string konu { get; set; }
        public string cevap { get; set; }
        public string tarih { get; set; }
        public string okunma { get; set; }
        public string mesajID { get; set; }
    }
}
