//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCinema.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cinemaDB : DbContext
    {
        public cinemaDB()
            : base("name=cinemaDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<kategoriler> kategoriler { get; set; }
        public DbSet<makaleler> makaleler { get; set; }
        public DbSet<uyeler> uyeler { get; set; }
        public DbSet<mesajlar> mesajlar { get; set; }
        public DbSet<cevaplar> cevaplar { get; set; }
        public DbSet<urunler> urunler { get; set; }
        public DbSet<resimler> resimler { get; set; }
        public DbSet<HomeLayoutModule> HomeLayoutModule { get; set; }
    }
}
