//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCinema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IletisimBilgileri
    {
        public int id { get; set; }
        public string adres { get; set; }
        public string tel1 { get; set; }
        public string tel2 { get; set; }
        public string tel3 { get; set; }
        public string gsm1 { get; set; }
        public string gsm2 { get; set; }
        public string gsm3 { get; set; }
        public string google_maps { get; set; }
        public string facebook_adress { get; set; }
        public string twitter_adress { get; set; }
        public string instagram_adress { get; set; }
    }
}
