//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCinema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class makaleler
    {
        public int id { get; set; }
        public string kategoriID { get; set; }
        public string icerik { get; set; }
        public string anahtarKelimeler { get; set; }
        public string onay { get; set; }
        public string baslik { get; set; }
    }
}
