//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCinema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mesajlar
    {
        public int id { get; set; }
        public string gonderen { get; set; }
        public string konu { get; set; }
        public string mesaj { get; set; }
        public string tarih { get; set; }
        public string okunma { get; set; }
    }
}
