//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCinema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeoOptimizasyonu
    {
        public int id { get; set; }
        public string google_analytic_code { get; set; }
    }
}
