//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCinema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteAyarlari
    {
        public int id { get; set; }
        public string site_title { get; set; }
        public string site_description { get; set; }
        public string site_slogan { get; set; }
        public string site_keyword { get; set; }
    }
}
