//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCinema.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class urunler
    {
        public int id { get; set; }
        public string UrunKodu { get; set; }
        public string UrunAdi { get; set; }
        public string UrunResmi { get; set; }
        public string UrunResimleri { get; set; }
        public string UrunAciklamasi { get; set; }
        public string UrunEtiketleri { get; set; }
        public string UrunFiyati { get; set; }
        public string UrunOnayi { get; set; }
        public string UrunStokAdeti { get; set; }
        public string UrunKategoriID { get; set; }
    }
}
